/**
 * Local asset paths: icons (MIT, see assets/THIRD_PARTY.txt) + patch backgrounds (original SVG).
 * patchMap keys tie stratagem ids to thematic drops; omitted ids use "base".
 */
(function () {
  const P = "assets/backgrounds/";
  const patchFiles = {
    base: `${P}patch-base.svg`,
    cuttingEdge: `${P}patch-cutting-edge.svg`,
    siegeDust: `${P}patch-siege-dust.svg`,
    controlUrbanChem: `${P}patch-control-urban-chem.svg`,
    pythonEntrenched: `${P}patch-python-entrenched.svg`,
    mastersMisc: `${P}patch-masters-misc.svg`,
    vehicles: `${P}patch-vehicles.svg`,
  };

  /** @type {Record<string, string>} stratagem id -> svg filename in assets/images/stratagems/ */
  const iconMap = {
    "mg-43": "machine_gun.svg",
    "eat-17": "expendable_anti-tank.svg",
    "m-105-stalwart": "stalwart.svg",
    "las-98": "laser_cannon.svg",
    "apw-1": "anti-materiel_rifle.svg",
    "gr-8": "recoilless_rifle.svg",
    "gl-21": "grenade_launcher.svg",
    "flam-40": "flamethrower.svg",
    "mg-206": "heavy_machine_gun.svg",
    "ac-8": "autocannon.svg",
    "arc-3": "arc_thrower.svg",
    "las-99": "quasar_cannon.svg",
    "rl-77": "rocket_sentry.svg",
    "mls-4x": "spear.svg",
    "faf-14": "spear.svg",
    "rs-422": "railgun.svg",
    "sta-x3": "eagle_110mm_rocket_pods.svg",
    "cqc-20": "heavy_machine_gun.svg",
    "plas-45": "laser_cannon.svg",
    "s-11": "spear.svg",
    "eat-700": "eagle_napalm_airstrike.svg",
    "eat-411": "expendable_anti-tank.svg",
    "gl-52": "grenade_launcher.svg",
    "cqc-9": "flamethrower.svg",
    "tx-41": "flamethrower.svg",
    "gl-28": "grenade_launcher.svg",
    "ms-11": "orbital_120mm_he_barrage.svg",
    "b-flam-80": "flamethrower.svg",
    "m-1000": "heavy_machine_gun.svg",
    "b-md-c4": "hellbomb.svg",
    "cqc-1": "super_earth_flag.svg",
    "orbital-precision": "orbital_precision_strike.svg",
    "orbital-gatling": "orbital_gatling_barrage.svg",
    "orbital-gas": "orbital_gas_strike.svg",
    "orbital-120mm": "orbital_120mm_he_barrage.svg",
    "orbital-airburst": "orbital_airburst_strike.svg",
    "orbital-smoke": "orbital_smoke_strike.svg",
    "orbital-ems": "orbital_ems_strike.svg",
    "orbital-380mm": "orbital_380mm_he_barrage.svg",
    "orbital-walking": "orbital_walking_barrage.svg",
    "orbital-laser": "orbital_laser.svg",
    "orbital-napalm": "eagle_napalm_airstrike.svg",
    "orbital-railcannon": "orbital_railcannon_strike.svg",
    "eagle-strafe": "eagle_strafing_run.svg",
    "eagle-airstrike": "eagle_airstrike.svg",
    "eagle-cluster": "eagle_cluster_bomb.svg",
    "eagle-napalm": "eagle_napalm_airstrike.svg",
    "eagle-smoke": "eagle_smoke_strike.svg",
    "eagle-rockets": "eagle_110mm_rocket_pods.svg",
    "eagle-500kg": "eagle_500kg_bomb.svg",
    "jump-pack": "jump_pack.svg",
    "md-6": "anti-personnel_minefield.svg",
    "md-i4": "incendiary_mines.svg",
    "md-17": "incendiary_mines.svg",
    "fx-12": "shield_generator_relay.svg",
    "e-mg-101": "hmg_emplacement.svg",
    "e-gl-21": "grenade_launcher.svg",
    "md-8": "orbital_gas_strike.svg",
    "e-at-12": "rocket_sentry.svg",
    "a-mg-43": "machine_gun_sentry.svg",
    "a-g-16": "gatling_sentry.svg",
    "a-ac-8": "autocannon_sentry.svg",
    "a-m-12": "mortar_sentry.svg",
    "a-mls-4x": "rocket_sentry.svg",
    "a-arc-3": "tesla_tower.svg",
    "a-m-23": "ems_mortar_sentry.svg",
    "a-las-98": "laser_cannon.svg",
    "a-flam-40": "flamethrower.svg",
    "a-gm-17": "mortar_sentry.svg",
    "b-1-supply": "supply_pack.svg",
    "sh-20": "ballistic_shield_backpack.svg",
    "ax-ar-23": "guard_dog.svg",
    "ax-las-5": "guard_dog_rover.svg",
    "sh-32": "shield_generator_pack.svg",
    "sh-51": "shield_generator_pack.svg",
    "ax-flam-75": "guard_dog.svg",
    "b-100": "hellbomb.svg",
    "ax-arc-3": "guard_dog.svg",
    "lift-860": "jump_pack.svg",
    "ax-tx-13": "guard_dog.svg",
    "lift-182": "jump_pack.svg",
    "exo-45": "patriot_exosuit.svg",
    "exo-49": "patriot_exosuit.svg",
    "m-102": "patriot_exosuit.svg",
    "td-220": "patriot_exosuit.svg",
    reinforce: "reinforce.svg",
    resupply: "resupply.svg",
    sos: "sos_beacon.svg",
    "eagle-rearm": "eagle_rearm.svg",
    "call-super-destroyer": "orbital_precision_strike.svg",
    "illumination-flare": "orbital_illumination_flare.svg",
    hellbomb: "hellbomb.svg",
    "seismic-probe": "seismic_probe.svg",
    "upload-data": "upload_data.svg",
    sssd: "sssd_delivery.svg",
    "super-flag": "super_earth_flag.svg",
    seaf: "seaf_artillery.svg",
  };

  /** @type {Record<string, keyof typeof patchFiles>} */
  const patchMap = {
    "las-99": "cuttingEdge",
    "rl-77": "cuttingEdge",
    "mls-4x": "cuttingEdge",
    "mg-206": "cuttingEdge",
    "sta-x3": "cuttingEdge",
    "orbital-napalm": "cuttingEdge",
    "cqc-20": "siegeDust",
    "eat-411": "siegeDust",
    "gl-28": "siegeDust",
    "b-md-c4": "siegeDust",
    "s-11": "siegeDust",
    "eat-700": "siegeDust",
    "ms-11": "siegeDust",
    "plas-45": "controlUrbanChem",
    "a-las-98": "controlUrbanChem",
    "lift-182": "controlUrbanChem",
    "sh-51": "controlUrbanChem",
    "a-flam-40": "controlUrbanChem",
    "e-at-12": "controlUrbanChem",
    "tx-41": "controlUrbanChem",
    "ax-tx-13": "controlUrbanChem",
    "ax-flam-75": "pythonEntrenched",
    "m-1000": "pythonEntrenched",
    "cqc-9": "pythonEntrenched",
    "b-flam-80": "pythonEntrenched",
    "a-gm-17": "pythonEntrenched",
    "gl-52": "pythonEntrenched",
    "ax-arc-3": "pythonEntrenched",
    "cqc-1": "mastersMisc",
    "b-100": "mastersMisc",
    "lift-860": "mastersMisc",
    "exo-49": "vehicles",
    "m-102": "vehicles",
    "td-220": "vehicles",
  };

  window.HD2_ASSETS = {
    stratagemIconDir: "assets/images/stratagems/",
    placeholderIcon: "placeholder.svg",
    superEarthSvg: "assets/images/super_earth.svg",
    iconMap,
    patchMap,
    patchFiles,
    resolvePatchKey(stratId) {
      return patchMap[stratId] || "base";
    },
    resolvePatchUrl(stratId) {
      const k = patchMap[stratId] || "base";
      return patchFiles[k] || patchFiles.base;
    },
    resolveStratagemIconUrl(stratId, overrideFile) {
      const dir = window.HD2_ASSETS.stratagemIconDir;
      if (overrideFile && String(overrideFile).trim()) {
        return dir + String(overrideFile).trim().replace(/^.*[\\/]/, "");
      }
      const f = iconMap[stratId];
      return f ? dir + f : dir + window.HD2_ASSETS.placeholderIcon;
    },
  };
})();
